---
# Paths to the checkpoint-xyz/ directory containing the checkpoint to load the model and any other products of training from.
checkpoint_dirs:
    - /data/D20_CV_V2/linear_increasing_lambda_scheduler_fold_0_2025-11-12_01-01-33/model.safetensors
    - /data/D20_CV_V2/linear_increasing_lambda_scheduler_fold_1_2025-11-12_03-44-10/model.safetensors
    - /data/D20_CV_V2/linear_increasing_lambda_scheduler_fold_2_2025-11-12_06-27-25/model.safetensors
    - /data/D20_CV_V2/linear_increasing_lambda_scheduler_fold_3_2025-11-12_09-09-04/model.safetensors
    - /data/D20_CV_V2/linear_increasing_lambda_scheduler_fold_4_2025-11-12_11-50-39/model.safetensors
output_dir: /repo/results/metrics/final_results/dann_target_domain_Rotated_90deg/Uniform_Noise/
architecture:
    # This directory is expected to contain `model.safetensors` at minimum.
    # This directory would have been produced by using `run_training.py`.
    cls_name: ResNet50DANN
    cls_init_args:
        num_classes: 11
        # Irrelevant to evaluation, but must be provided to instantiate the model object.
        lamb_initial: 0.0
        ld_scale: 1.0
evaluation:
    evaluator:
        cls_name: DANNTrainer
    dataset:
        cls_name: TwoLabelDataset
        convert_grayscale_to_rgb: True
        fold_file_paths:
            - /data/DG_Test_set/test_dataset_Uniform_Noise.npz
    evaluation_arguments:
        batch_size: 32
