---
log_dir: /repo/results/logs/
architecture:
    cls_name: ResNet50DANN
    cls_init_args:
        num_classes: 11
        lamb_initial: 0.0
        ld_scale: 1.0
# TODO - support 5-fold CV
training:
    trainer:
        cls_name: DANNTrainer
    dataset:
        cls_name: TwoLabelDataset
        cls_train_load_args:
            file_path: /data/D21_preprocessed/D21_preprocessed_train_v2.npz
            convert_grayscale_to_rgb: True
        cls_eval_load_args:
            file_path: /data/D21_preprocessed/D21_preprocessed_val_v2.npz
            convert_grayscale_to_rgb: True
    training_arguments:
        output_dir: /data/D21_train_results/
        num_train_epochs: 3
        batch_size: 32
        learning_rate: 0.1
        weight_decay: 0.0001
        optim: sgd
        resume_from_checkpoint: False
    lambda_scheduler: parabolic_increasing_lambda_scheduler

evaluation:
    evaluator:
        cls_name: DANNTrainer
    dataset:
        cls_name: TwoLabelDataset
        cls_eval_load_args:
            file_path: /data/D21_preprocessed/D21_preprocessed_val_v2.npz
            convert_grayscale_to_rgb: True
    output_dir: /data/D21_eval_results/
    batch_size: 32
